exports.addons = {
	honey_boba: { name: 'honey boba', price: 0.7, image: '' },
	crystal_boba: { name: 'crystal boba', price: 0.7, image: '' },
	egg_pudding: { name: 'egg pudding', price: 0.7, image: '' },
	taro_pudding: { name: 'taro pudding', price: 0.7, image: '' },
	aloe_vera: { name: 'aloe vera', price: 0.7, image: '' },
	grass_jelly: { name: 'grass jelly', price: 0.7, image: '' },
	rainbow_jelly: { name: 'rainbow jelly', price: 0.7, image: '' },
	red_bean: { name: 'red bean', price: 0.7, image: '' },
	cheese_ball: { name: 'cheese ball', price: 1.0, image: '' },
	cheese_foam: { name: 'cheese foam', price: 1.0, image: '' },
};
exports.items = {
	'01': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'02': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'03': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'04': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'05': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'06': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'07': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'08': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	'09': {
		name: 'Milk Tea 01',
		category: 'Milk Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	10: {
		name: 'Smoothie',
		category: 'Smoothie',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	11: {
		name: 'Smoothie',
		category: 'Smoothie',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	12: {
		name: 'Smoothie',
		category: 'Smoothie',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	13: {
		name: 'Smoothie',
		category: 'Smoothie',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	14: {
		name: 'Fruit tea',
		category: 'Fruit Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
	15: {
		name: 'Fruit tea',
		category: 'Fruit Tea',
		price: 5.0,
		addon: [this.addons.honey_boba.name],
		description: '',
		image: '',
	},
};
